# Generated by Django 3.0.2 on 2020-07-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0002_auto_20200705_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchats',
            name='msgtype',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ImageUploadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.TextField()),
                ('filename', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('msgtype', models.IntegerField(default=0)),
                ('sender', models.CharField(default='-', max_length=20)),
                ('chatconnect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentimages', to='usergroups.Groups')),
            ],
            options={
                'verbose_name_plural': 'ImageUploadGroup',
            },
        ),
    ]
