# Generated by Django 3.0.2 on 2020-07-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0003_auto_20200715_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUploadGroup',
        ),
    ]
