# Generated by Django 3.0.2 on 2020-07-15 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usergroups', '0004_delete_imageuploadgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.TextField()),
                ('filename', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('msgtype', models.IntegerField(default=0)),
                ('chatconnect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentimages', to='usergroups.Groups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagessent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ImageUploadGroup',
            },
        ),
    ]
