# Generated by Django 3.0.2 on 2020-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0005_imageuploadgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='actual',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
