# Generated by Django 3.0.2 on 2020-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0006_groups_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='groupic',
            field=models.TextField(default='-'),
        ),
    ]
