# Generated by Django 3.0.2 on 2020-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profilepic',
            field=models.TextField(default='-'),
        ),
    ]
