# Generated by Django 3.0.2 on 2020-07-18 19:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media 2/profilepic'), upload_to='')),
                ('user', models.CharField(default='-', max_length=20)),
            ],
        ),
    ]
