# Generated by Django 3.0.2 on 2020-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200718_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(default='-'),
        ),
    ]
