# Generated by Django 3.0.2 on 2020-07-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalchats',
            options={'verbose_name_plural': 'PersonalChats'},
        ),
    ]
