# Generated by Django 3.0.2 on 2020-07-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
