# Generated by Django 3.0.2 on 2020-07-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.TextField()),
                ('filename', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('chatconnect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentimages', to='main.PersonalChats')),
            ],
            options={
                'verbose_name_plural': 'ImageUploads',
            },
        ),
    ]
