# Generated by Django 3.0.2 on 2020-07-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalchats',
            name='msg_type',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.TextField()),
                ('filename', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('msgtype', models.IntegerField(default=0)),
                ('sender', models.CharField(default='-', max_length=20)),
                ('chatconnect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentimages', to='main.Friends')),
            ],
            options={
                'verbose_name_plural': 'ImageUploads',
            },
        ),
    ]
