# Generated by Django 3.0.2 on 2020-07-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200715_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalchats',
            old_name='msg_type',
            new_name='msgtype',
        ),
    ]
